version: '3.3'
services:
  php:
    image: secrets_php:latest
    build:
      context: "./docker/php"
      args: { }
    command: "php /var/www/html/index.php"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
     MONGODB_URI_FILE: /run/secrets/mongodburidockersecret
    secrets:
      - mongodburidockersecret
secrets:
  mongodburidockersecret:
    external: true
